### ISSUE TITLE
Add to Packagist

### ISSUE THREAD

**Issue by jerrylopez** [bitpay/bitpay-checkout-magento2#22]
Can this module be added to packagist.org? 

Currently, the only way to install this would be by copying the files into `app/code` or artifact composer repository in a project.

**Comment by davidwindell** [comment]
Please do add this to packagist, it would require moving the composer.json into the root.

**Comment by jorgb90** [comment]
Yes please do!

**Comment by bobbrodie** [comment]
Hello! I know this one is quite old at this point, but we are working on updates and have set up the module with Packagist. We are about to tag a new version, and will have follow-ups in the coming weeks.
