### ISSUE TITLE
Checkout error

### ISSUE THREAD

**Issue by kishyr** [bitpay/bitpay-checkout-magento2#25]
Using the Test environment, upon checking out, our Magento 2.2.9 site goes from the payments screen on checkout directly to order success without redirecting or showing the BitPay modal. On the success page (`checkout/onepage/success/`), the following error is shown:

```
1 exception(s):
Exception #0 (Exception): Notice: Undefined property: stdClass::$data in /var/www/html/app/code/Bitpay/BPCheckout/Observer/BPRedirect.php on line 310
```

We are using version 3.1.1911.0 of the plugin on Magento 2.2.9. Are these two versions compatible? Any tips on how to debug this or figure out where things are going wrong?

Thank you.

**Comment by thejoshualewis** [comment]
Hi @kishyr ,

Email us at integrations@bitpay.com with this issue number, and if you can let us know the account you signed up for on test we we can look and see if your account setup is complete.

You can also set the option from Modal to Redirect in the admin section, this will just send a user to bitpay to pay, and then redirect them.  If that doesnt work, its most likely an account issue.
