### ISSUE TITLE
XML Validation Error on Route Configuration

### ISSUE THREAD

**Issue by vbuck** [bitpay/bitpay-checkout-magento2#27]
In developer mode, XML validation fails on `etc/frontend/routes.xml` because it contains an empty body:

```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/vagrant/magento/vendor/bitpay/module-bpcheckout/etc/frontend/routes.xml" is invalid:
Element 'config': Missing child element(s). Expected is ( router ).
Line: 2

Verify the XML and try again.
```

## Steps to Reproduce

 1. Install the module
 2. Enable developer mode
 3. Ensure config cache has been flushed
 4. Attempt to navigate to the frontend
 5. Observe exception

Because there are no actual controllers used on the frontend, this configuration file and be removed, and that will resolve the error.

**Comment by vbuck** [comment]
I forked and created a proposal PR to solve for this issue.

**Comment by thejoshualewis** [comment]
Thanks, merged and will be submitting
