### ISSUE TITLE
Add payment logo in checkout

### ISSUE THREAD

**Issue by jorgb90** [bitpay/bitpay-checkout-magento2#58]
All our payment methods are having a payment logo in front of their name in the checkout except for Bitpay. I think it would be great if Bitpay would add this as well. This way it gets more attention and it will also help with brand exposure.

**Comment by p-maguire** [comment]
@jorgb90 Thanks for the suggestion, we are planning to implement this in the next release! I'm going to close this issue out since we have an internal ticket tracking it.
